# Generated by Django 5.1.3 on 2025-01-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=50)),
                ('service_tag', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('license_expired_date', models.DateField()),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='datacenter_app.datacenter')),
            ],
        ),
    ]
