# Generated by Django 5.2.1 on 2025-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0002_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
